### ISSUE TITLE
cloud storage

### ISSUE THREAD

**Issue by rafeerahman** [CSC207-UofT/course-project-xep-cgamerzx#29]
Problem: Users should be able to view the same hotels after downloading the app on their phone.

The only way to do this is save the hotelier database to some server or cloud storage? Then when **any** user opens the app they have the same data being listed.

**Comment by hk21702** [comment]
Moving to firestore for cloud and persistent data.

**Comment by hk21702** [comment]
Might abandon

**Comment by hk21702** [comment]
Outside of scope
