### ISSUE TITLE
Backend with new RoomsLibrary db

### ISSUE THREAD

**Issue by rafeerahman** [CSC207-UofT/course-project-xep-cgamerzx#30]
Need to use the new structure to save data.

When the new front end files are created in the management, hotel list, and the "explore" search xml files,  we need to use the inputs, and save/display them (basically hotel objects) using our new structure in their respective activities.

_Explore page is created, TODO is management a hotel list _

https://www.figma.com/file/puMnb2v1uDQA2CoQMzFEqR/hotelier?node-id=0%3A1

**Comment by hk21702** [comment]
Migration done. See #33
