### ISSUE TITLE
A constant for all Cities, Countries, States

### ISSUE THREAD

**Issue by rafeerahman** [CSC207-UofT/course-project-xep-cgamerzx#31]
In the search option, when typing in a destination, a dropdown appears with suggested cities. Write now, I used dummy data with New York, Toronto, Ottawa. However, this should ideally be data with every city. So for example, when I type in Vancouver, a suggestion for Vancouver, BC, Canada should show. 

^ To look at this feature currently, you should click search in the UI-updating branch and type in "Toronto" as an example to see how it works. The backend code is in the SearchFragment.java file.

any ideas on where/how to store this data on cities/countries would be good.

**Comment by hk21702** [comment]
This should ideally be something taken from a 3rd party library/source/api

**Comment by hk21702** [comment]
Implemented somewhat using google maps api
